source("./loaddata.R")
png("plot4.png")
par(mfrow=c(2,2))
plot(times,limited[,"Global_active_power"], type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(times,limited[,"Voltage"], type="l", xlab="datetime",ylab="Voltage")

plot(times,limited[,"Sub_metering_1"], type="l", xlab="",ylab="Energy sub metering")
lines(times,limited[,"Sub_metering_2"],col="red")
lines(times,limited[,"Sub_metering_3"], col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"),lty=1)
plot(times,limited[,"Global_reactive_power"], type="l", xlab="datetime",ylab="Global_reactive_power")
dev.off()